#
# Builds the Wrappers for various languages
#
#

SWIG_FILE	:= AIOUSB.i	 
SWIG		:= swig

PERL		:= perl
PYTHON		:= python
RUBY		:= ruby

MKDIR		:= mkdir

LIBDIR		:= $(shell printenv AIOUSB_ROOT)/lib
CLASSLIBDIR	:= $(shell printenv AIOUSB_ROOT)/classlib


PYTHON_LDFLAGS	:= -L$(LIBDIR) -L$(CLASSLIBDIR)
RUBY_LDFLAGS	:= $(PYTHON_LDFLAGS)

RUBY_INCLUDES	:= -I$(LIBDIR)
PERL_INCLUDES	:= -I$(shell printenv AIOUSB_ROOT)/lib

RUBY_BUILT	:= ruby_built.txt


PERL_CFLAGS	:= $(shell perl -MConfig -e "print \$$Config{ccflags}")
PERL_XTRA_CFLAGS:= -std=gnu99 -fno-merge-constants

ifdef PERL_PREFIX
PERL_PREFIX_INSTALL	:= PREFIX=$(PERL_PREFIX)
else 
PERL_PREFIX_INSTALL	:= 
endif
PYTHON_PREFIX	:= 

JAVA_DIR	:= com/accesio
JAVA_ROOT	:= com

TEST_DIR	:=	test_dir


clean:
	-rm -rf build
	if [ -f Makefile ] ;  then  $(MAKE) -f Makefile clean ; fi
	-rm -f *~	
	-rm -f AIOUSB_wrap.c
	-rm -f AIOUSB.py*
	-rm -f *.pm
	-rm -f Makefile.old
	-rm -f Makefile
	-rm -f *.log
	-rm -f *.o
	-rm -f *.oct
	-rm -f *wrap.*
	-rm -f *.java
	-rm -f *.php
	-rm -fr $(JAVA_ROOT)
	-rm -f *.class
	-rm -f *.so
	-rm -rf target
	-rm -rf ruby_built.txt

all:
	$(MAKE)	-f GNUMakefile perl_install
	$(MAKE) -f GNUMakefile python_install
	$(MAKE) -f GNUMakefile ruby_install

precheck:


perl:
	$(SWIG) $(PERL_INCLUDES)  -perl5 AIOUSB.i 
	$(PERL) Makefile.PL CCFLAGS="$(PERL_CFLAGS) $(PERL_XTRA_CFLAGS)" $(PERL_PREFIX_INSTALL)
	$(MAKE) -f Makefile 

perl_test:	perl $(TEST_DIR)
	@perl -I../blib/arch/ -MAIOUSB -e 'AIOUSB::AIOUSB_Init(); AIOUSB::AIOUSB_ListDevices()'


perl_install:  perl
	$(MAKE) -f Makefile install 

python: 
	$(SWIG) -I${LIBDIR}  -python AIOUSB.i
	LDFLAGS="$(PYTHON_LDFLAGS)"  python setup.py build

$(TEST_DIR):
	mkdir -f $(TEST_DIR)

python_test: $(TEST_DIR)
	@cd $(TEST_DIR) && PYTHONPATH=$${PWD}/../build/lib.linux-x86_64-2.7 python -c 'import AIOUSB; AIOUSB.AIOUSB_Init(); AIOUSB.AIOUSB_ListDevices()'


python_install: python
	$(PYTHON) setup.py install --prefix=$(PYTHON_PREFIX)

#
# RUBY
#
ruby:
	@if [ ! -f $(RUBY_BUILT) ] ; then \
		$(SWIG) -I../ -ruby AIOUSB.i; \
		$(RUBY) extconf.rb --with-ldflags="$(RUBY_LDFLAGS)" --with-name-include="$(RUBY_INCLUDES)"; \
		$(MAKE) -f Makefile;\
		touch $(RUBY_BUILT); fi

$(RUBY_BUILT): ruby

ruby_test:	$(RUBY_BUILT) $(TEST_DIR)
	@cd $(TEST_DIR) && ruby -I.. -rAIOUSB  -e 'AIOUSB.AIOUSB_Init(); AIOUSB.AIOUSB_ListDevices()'


ruby_install: ruby_test
	$(MAKE) -f Makefile install

#
# PHP
#


php:
	$(SWIG) -I../ -php AIOUSB.i
	$(CC) -I. -I../  $$(php-config --includes) -fpic -c AIOUSB_wrap.c
	$(CC) -shared AIOUSB_wrap.o -o AIOUSB.so

#
# OCTAVE
#

octave:
	$(SWIG) -I../ -octave -o AIOUSB_wrap.cpp AIOUSB.i
	mkoctfile -o AIOUSB.oct  -I.. AIOUSB_wrap.cpp -L$$AIOUSB_ROOT/lib -L$$AIOUSB_ROOT/classlib -laiousb

octave_test:
	@octave -q  --eval "AIOUSB; AIOUSB.AIOUSB_Init(); AIOUSB.AIOUSB_ListDevices();"


#
# JAVA
#

$(JAVA_DIR):
	$(MKDIR) -p $@

java: 	$(JAVA_DIR)
	$(SWIG) -I../ -java -package com.accesio -outdir $(JAVA_DIR) AIOUSB.i
	$(CC) -fPIC -I../  -I/usr/include/libusb-1.0 -I/usr/lib/jvm/java-7-openjdk-amd64/include -L$${AIOUSB_ROOT}/lib -L$${AIOUSB_ROOT}/classlib -c AIOUSB_wrap.c
	$(CC)  -shared -I../  -I/usr/lib/jvm/java-7-openjdk-amd64/include ./AIOUSB_wrap.o -L$$AIOUSB_ROOT/lib -L$$AIOUSB_ROOT/classlib   -lusb-1.0 -lpthread -laiousbdbg  -laiousbcppdbg  -o libAIOUSB.so
	cd tests && javac -classpath "/home/jdamon/Projects/aiousb_coding/AIOUSB/AIOUSB/lib/wrappers:" test.java


java_test:
	@scala -e 'import com.accesio._;  AIOUSB.AIOUSB_Init(); AIOUSB.AIOUSB_ListDevices()'

