#
# Builds the Wrappers for various languages
#
#

SWIG_FILE	:= AIOUSB.i	 
SWIG		:= swig

PERL		:= perl
PYTHON		:= python
RUBY		:= ruby

LIBDIR		:= $(shell printenv AIOUSB_ROOT)/lib
CLASSLIBDIR	:= $(shell printenv AIOUSB_ROOT)/classlib


PYTHON_LDFLAGS	:= -L$(LIBDIR) -L$(CLASSLIBDIR)
RUBY_LDFLAGS	:= $(PYTHON_LDFLAGS)

RUBY_INCLUDES	:= -I$(LIBDIR)
PERL_INCLUDES	:= -I$(shell printenv AIOUSB_ROOT)/lib


ifdef PERL_PREFIX
PERL_PREFIX_INSTALL	:= PREFIX=$(PERL_PREFIX)
else 
PERL_PREFIX_INSTALL	:= 
endif
PYTHON_PREFIX	:= 


clean:
	-rm -rf build
	if [ -f Makefile ] ;  then  $(MAKE) -f Makefile clean ; fi
	-rm -f *~	
	-rm -f AIOUSB_wrap.c
	-rm -f AIOUSB.py
	-rm -f *.pm
	-rm -f Makefile.old
	-rm -f *.log
	-rm -f *.o

all:
	$(MAKE)	-f GNUMakefile perl_install
	$(MAKE) -f GNUMakefile python_install
	$(MAKE) -f GNUMakefile ruby_install

perl:
	$(SWIG) $(PERL_INCLUDES)  -perl5 AIOUSB.i 
	$(PERL) Makefile.PL $(PERL_PREFIX_INSTALL)
	$(MAKE) -f Makefile 


perl_install:  perl
	$(MAKE) -f Makefile install 

python: 
	$(SWIG) -I${LIBDIR}  -python AIOUSB.i
	LDFLAGS="$(PYTHON_LDFLAGS)"  python setup.py build

python_install: python
	$(PYTHON) setup.py install --prefix=$(PYTHON_PREFIX)

ruby:
	$(RM) -f Makefile
	$(SWIG) -I../ -ruby AIOUSB.i
	$(RUBY) extconf.rb --with-ldflags="$(RUBY_LDFLAGS)" --with-name-include="$(RUBY_INCLUDES)"
	$(MAKE) -f Makefile 

ruby_install: ruby
	$(MAKE) -f Makefile install