#
# Builds the Wrappers for various languages
#
#

SWIG_FILE	:= AIOUSB.i	 
SWIG		:= swig

PERL		:= perl
PYTHON		:= python
RUBY		:= ruby

LIBDIR		:= $(shell printenv AIOUSB_ROOT)/lib
CLASSLIBDIR	:= $(shell printenv AIOUSB_ROOT)/classlib

PYTHON_LDFLAGS	:= -L$(LIBDIR) -L$(CLASSLIBDIR)

ifdef PERL_PREFIX
PERL_PREFIX_INSTALL	:= PREFIX=$(PERL_PREFIX)
else 
PERL_PREFIX_INSTALL	:= 
endif
PYTHON_PREFIX	:= 


clean:
	-rm -rf build
	if [ -f Makefile ] ;  then  $(MAKE) -f Makefile clean ; fi
	-rm -f *~	
	-rm -f AIOUSB_wrap.c
	-rm -f *.pyc
	-rm -f Makefile.old

perl:
	$(SWIG) -I${LIBDIR}  -perl5 AIOUSB.i 
	$(PERL) Makefile.PL $(PERL_PREFIX_INSTALL)
	$(MAKE) -f Makefile 


perl_install:  perl
	$(MAKE) -f Makefile install 

python: 
	$(SWIG) -I${LIBDIR}  -python AIOUSB.i
	LDFLAGS="$(PYTHON_LDFLAGS)"  python setup.py build

python_install:
	$(PYTHON) setup.py install --prefix=$(PYTHON_PREFIX)

ruby:

ruby_install:
	$(RUBY) 